# Generated by Django 4.1.5 on 2023-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('vat', models.FloatField(choices=[(0.23, '0.23'), (0.08, '0.08'), (0.05, '0.05'), (0, '0')])),
                ('stock', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(to='cinema_app.category')),
            ],
        ),
    ]
